In [2]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[0,2,4,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [0 2 4 8]]


In [4]:
b=np.zeros((4,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
c=np.full((4,3),3)
print(c)

[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


In [10]:
d=np.random.random((4,3))
print(d)

[[0.68619212 0.22430132 0.71734634]
 [0.33128561 0.78612964 0.51658779]
 [0.81957196 0.05707727 0.83605305]
 [0.22997466 0.07668429 0.06041783]]


In [12]:
e=np.arange(3,36,5)
print(e)

[ 3  8 13 18 23 28 33]


In [16]:
print(c.reshape(3,4))

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [17]:
print(c.flatten())

[3 3 3 3 3 3 3 3 3 3 3 3]


In [18]:
print(c.ndim)

2


In [19]:
print(c.dtype)

int32


In [20]:
print(c.astype('f'))

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [21]:
print(a[0:3:2])

[[1 2 3 4]
 [0 2 4 8]]


In [22]:
print(a[2::])

[[0 2 4 8]]


In [23]:
print(a[1,0:4])

[5 6 7 8]


In [24]:
print(a[1,2:4])

[7 8]


In [26]:
print(a[2,1:4])

[2 4 8]


In [27]:
print(a[:1])

[[1 2 3 4]]


In [3]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [5]:
print(a[1:3:2])

[[2 3 4 5]]


In [9]:
print(a[1:3:1])

[[2 3 4 5]
 [3 4 5 6]]


In [14]:
print(a[:2,:3]) #first 2 rows and 3 columns

[[1 2 3]
 [2 3 4]]


In [13]:
print(a[:3,:2])

[[1 2]
 [2 3]
 [3 4]]


In [15]:
print(a[[0,1,2],[1,2,3]]) #(0,1)(1,2)(2,3)

[2 4 6]


In [17]:
print(a[[0,1,2],[3,2,1]])

[4 4 4]


In [19]:
cond=a>2
print(a[cond]) #elements greater than 2

[3 4 3 4 5 3 4 5 6]


In [59]:

print(a[a>=5])

[5 5 6]


In [29]:
print(a[::2])

[[1 2 3 4]
 [3 4 5 6]]


In [31]:
print(a[1::])

[[2 3 4 5]
 [3 4 5 6]]


In [34]:
print(a[:2:])

[[1 2 3 4]
 [2 3 4 5]]


In [42]:
a1=np.array([6,7,8,9])
a2=np.array([2,3,4,5])
arr=np.concatenate((a2,a1))
print(arr)

[2 3 4 5 6 7 8 9]


In [52]:
a3=np.array([[6,7,8,9],[1,2,3,4]])
a4=np.array([[2,3,4,5],[1,5,7,9]])
arr=np.concatenate((a3,a4))
print(arr)

[[6 7 8 9]
 [1 2 3 4]
 [2 3 4 5]
 [1 5 7 9]]


In [45]:
arr1=np.hstack((a1,a2))
print(arr1)            #horizontal stack

[6 7 8 9 2 3 4 5]


In [47]:
arr1=np.vstack((a1,a2)) #vertical stack
print(arr1)

[[6 7 8 9]
 [2 3 4 5]]


In [49]:
arr1=np.dstack((a1,a2)) #depth join
print(arr1)

[[[6 2]
  [7 3]
  [8 4]
  [9 5]]]


In [57]:
arr=np.array([1,2,3,4,5,6,7])
a1=np.array_split(arr,3)
print(a1)
print(a1[0])
print(a1[1])
print(a1[2])

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[1 2 3]
[4 5]
[6 7]


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,5,5,6])
print(np.where(arr==5))

(array([4, 5, 6], dtype=int64),)


In [32]:
arr=np.array([1,2,3,4,5,6,7,8,9])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [33]:
x=np.searchsorted(arr,4,side='left')
print(x)

3


In [34]:
x=np.searchsorted(arr,4,side='right')
print(x)

4


In [35]:
arr=np.array([4,7,1,5,6])
print(np.sort(arr))

[1 4 5 6 7]


In [36]:
arr=np.array([[7,2,1],[4,3,5]])
print(np.sort(arr))

[[1 2 7]
 [3 4 5]]


In [37]:
arr=np.array([41,42,43,44,45])
x=[True,False,True,False,True]
arr1=arr[x]
print(arr1)

[41 43 45]


In [38]:
arr=np.array([4,5,6,7,1,2])
x=arr>3
arr1=arr[x]
print(arr1)

[4 5 6 7]


In [39]:
import numpy as np
a=np.array([10,20,30,40,50,60])
b=np.array([3,6,9,12,15,18])
print(a)
print(b)

[10 20 30 40 50 60]
[ 3  6  9 12 15 18]


In [40]:
print(a+b) #vector addition

[13 26 39 52 65 78]


In [41]:
print(a-b) #vector subtraction

[ 7 14 21 28 35 42]


In [42]:
print(a*b) #vector multiplication

[  30  120  270  480  750 1080]


In [43]:
c=[2,4,5,8,10,12]
print(a/c) #vector division

[5. 5. 6. 5. 5. 5.]


In [44]:
print(a.dot(b)) #dot product

2730


In [45]:
s=5    #scalar multiplication
print(a*s)

[ 50 100 150 200 250 300]


In [49]:
def func(x,y):
    if(x>y):
        return(x-y)
    else:
        return(x+y)          #vectorize method
arr1=[10,20,30]
arr2=[2,4,60]
arr3=np.vectorize(func)
print(arr3(arr1,arr2))

[ 8 16 90]


In [50]:
def func(x,y):
    if(x>y):
        return(x-y)
    else:
        return(x+y)
arr1=[10,20,30]
arr2=[2,40,60]
arr3=np.vectorize(func)
print(arr3(arr1,arr2))

[ 8 60 90]
